### ISSUE TITLE
Support Bro dns.log processing

### ISSUE THREAD

**Issue by chrisforce1** [alphasoc/nfr#48]
If we can process the Bro `dns.log` format (by reading the file from the local filesystem) we can deploy NFR onto Bro IDS sensors and Corelight appliances to submit data to our API for scoring. The schema is described [here](https://www.bro.org/sphinx/scripts/base/protocols/dns/main.bro.html#type-DNS::Info) and we just need to pick up the `ts`, `id.orig_h`, `query`, and `qtype_name` values for each query.

**Comment by krhubert** [comment]
Done. https://github.com/alphasoc/nfr/commit/fc39fbbbcec2010f1b405eead0366cb2109a3408
